### ISSUE TITLE
Filtering transcriptions by group id, what about workflow?

### ISSUE THREAD

**Issue by zwolf** [zooniverse/text-editor#102]
The index page that filters transcriptions by group id sends a request to /transcriptions with the group_id in the filter params. Does this query also include the workflow_id to filter by? It's possible for a user to re-use a group id across subjects linked to different workflows, and without knowing the workflow id, a query like `where group_id = 'GROUP1'` will return transcriptions from every workflow. 

Including workflow_id as a filter param would also enable the backend to authorize the workflow (rather than each individual transcription), making that code simpler. I believe that workflow would be the correct scope, based on Nicole and I's "if you press this button on this page you'd expect to export the ones you're staring at" UX testing algorithm.

**Comment by wgranger** [comment]
Good point. I'll make sure to send over a workflow id, if I'm not already. Shouldn't be too hard to hook that up with each call.
