### ISSUE TITLE
Add help text to about page

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/text-editor#148]
Add the linked text to alice.zooniverse.org/about: [Google Doc](https://docs.google.com/document/d/1l47T0gScsUC6CiavmcWfPUdryFzF6nWYc2V0FsDdIfI/edit?usp=sharing)

Note: I will open a separate issue with a link to image files. Please use image file names as placeholders for the time being.

**Comment by wgranger** [comment]
Are the image files changing from that doc? If not, I can download and use the images on that Google doc.

**Comment by wgranger** [comment]
Also, how does this map to the current design on [invision](https://projects.invisionapp.com/d/#/console/17925240/394207098/preview)? Should all the images still appear to the right of the text, or should they appear between each text as they are in the google doc?

**Comment by snblickhan** [comment]
As of today (4/10) images are OK up to the Using ALICE section (those are not yet generated). The image folder is in [Google Drive](https://drive.google.com/drive/folders/1zTunYPCXs6jRqNSL-96kOTh1G2mR1Rk0?usp=sharing), and file names map to the ones in the Gdoc.

Regarding image placement, I'd defer to @beckyrother -- Becky, what do you think about where images should go on the ALICE About page?

**Comment by beckyrother** [comment]
Since some really need more detail than the small thumbnails will provide easily, can they go inline. Updated the invision to show – the text area shouldn't be wider than 900 px for optimal line length / ease of reading. 

https://projects.invisionapp.com/d/main#/console/17925240/394207098/preview
