### ISSUE TITLE
Help page design feedback

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/text-editor#151]
- [x] max width for the text block should be 800px (any wider and it gets hard to read) (does not apply to images, which can stay the same sizing as they currently are)
- [x] left-align images (ty Nicole)
- [x] add 1em spacing between paragraphs
- [x] max-width on H4 seems to be less than everywhere else? 
- [x] increase body font size to 16px

Contents:
Text weights for levels is good but
- [ ] Don't capitalize the secondary links
- [x] Add 1em between major sections (ie above 'Using ALICE with your team')

Elsewhere:
- [x] dropdown on profile is very tiny, add padding to top and bottom so each option has 44px height (#156)
current:
![image](https://user-images.githubusercontent.com/1392130/79385577-70728d00-7f2e-11ea-8998-d632f2d5eb18.png)
invision: 
![image](https://user-images.githubusercontent.com/1392130/79385743-b4659200-7f2e-11ea-92e9-4871b7514820.png)

**Comment by wgranger** [comment]
Referring to capitalization, what secondary links are you talking about? The only item I see that may need changing is Zooniverse Project Builder -> Zooniverse project builder? @beckyrother

**Comment by beckyrother** [comment]
I meant in the sidebar links, sorry: 
![Zooniverse_Text_Editor_and_Community_PlayLab_LOGIC_MODEL_-_Google_Docs](https://user-images.githubusercontent.com/1392130/79905258-94751900-83db-11ea-9a98-6cc635f03f9e.png)
