### ISSUE TITLE
Filmstrip Viewer Pagination Discrepancy 

### ISSUE THREAD

**Issue by wgranger** [zooniverse/text-editor#177]
There's a discrepancy with how we're displaying frames via the filmstrip viewer. 

Ex: We have a subject with two pages, and three slopes (two slopes on page one, one slope on page two). 

When the filmstrip viewer is **expanded**, we see options to view each slope. 
<img width="381" alt="Screen Shot 2020-07-01 at 2 52 29 PM" src="https://user-images.githubusercontent.com/14099077/86285642-99f49980-bbaa-11ea-9400-5934f7795740.png">

When the filmstrip viewer is **collapsed**, we see options for each page.
<img width="92" alt="Screen Shot 2020-07-01 at 2 52 59 PM" src="https://user-images.githubusercontent.com/14099077/86285634-96611280-bbaa-11ea-951c-afb16282bc84.png">

Note: I added the numbers on the second image to help me with debugging, but it may or may not stay? How can we reconcile these two images? 

For the collapsed view, it makes sense to add each slope that would be available, but how do we account for:
- Selecting the second circle, but this is page three since we have rearranged the pages?
- How do we account for there being two circles for the same page, one for each frame?

There's also the question, do we still need this collapsed view if it's going to make the messaging more confusing now that we have the ability to rearrange pages and display slope values for each page.

**Comment by wgranger** [comment]
Also, some notes from Shaun via Slack:

ODDITY 1: PHANTOM PAGES ON FILMSTRIP VIEWER
- Significant UI issue
- If a document has X+Y pages, and X pages have transcribed text but Y pages don't have any, then the Filmstrip Viewer displays them differently.
- If the filmstrip viewer is EXPANDED, it will list only X pages
- If the filmstrip viewer is COLLAPSED, it will list X+Y pages
- Example: a 2-page document. Second page has no transcribed text, even though there's a tiiiny bit of text on the page https://alice.zooniverse.org/projects/4973/workflows/5339/groups/15524/subjects/13982089/edit
- NOTE: you cannot Add a Line on a page without existing transcribed text.

ODDITY 2: MISSING 180º PAGES ON FILMSTRIP VIEWER
- If a document has 180º pages, those pages aren't listed when the Filmstrip Viewer is collapsed.
- Example: https://alice.zooniverse.org/projects/4973/workflows/5339/groups/15524/subjects/13982593/edit
- Not sure this is replicable across all Subjects, though.

**Comment by beckyrother** [comment]
The collapsed view was added because the initial design intent was to keep the filmstrip viewer always visible at the bottom of the screen. However, since this isn't happening (for the best, this way is better), collapsing the viewer to save screen space isn't as necessary. I'm in favor of removing that function entirely to avoid a lot of this confusion.

**Comment by wgranger** [comment]
Perfect. Removing the collapsed viewer will clean up some logic. I don't think we'll lose much by taking out this functionality, as I can't see a huge use case currently for collapsing the viewer
