### ISSUE TITLE
Possible Error 409 from Tove if submitting too many requests at a time

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/text-editor#187]
## Potential "Save Data" Bug

1. It's possible to get an Error 409 from Tove if you send too many POST/PUT/PATCH/whatever requests in one go.
2. Alice does not know how to handle an Error 409.

<img width="1280" alt="Screen Shot 2020-07-07 at 17 43 34" src="https://user-images.githubusercontent.com/13952701/86815048-20611d80-c07a-11ea-9f01-5aaaca9ac228.png">

### Dev Notes

Replication: (At least, what I did to consistently get the error above)

- Go to http://local.zooniverse.org:3000/projects/1764/workflows/3085/groups/12345/subjects/85068/edit
- Observe first transcribed line is "Boston March 3 - 1837", second line is "Friday noon"
- Click & drag to move "Boston March 3 - 1837" to second line (action 1)
- Click on "Boston March 3 - 1837" to open popup (action 2)
- Write new text: "BOSTON MARCH 3 - 1837". Click "Replace with Selected" (action 3)
- Click "Close" (action 4)
- Now RAPIDLY CLICK ON THE UNDO BUTTON 💥 💥 💥 💥 💥 💥 💥 💥 
- Expected: all 4 actions should be undone and saved to Tove
- Actual: it looks like actions 1 to 4 are undone in on the front end. Then, after a few seconds of blissful silence, the whole app crashes.
  - Console error message: `PATCH https://tove-staging.zooniverse.org/transcriptions/85068 409`
  - Further adventures in console error messages:
    ```
    getError.js:25 Uncaught (in promise) TypeError: Cannot read property 'error' of undefined
        at getError (getError.js:25)
        at TranscriptionsStore.js:309
    ```
  - After reloading, it's apparent that actions 2 to 4 are undone, but action 1 (rearranging to second line) remains saved to the database.

This is likely a race condition where two PATCH requests are occurring near-simultaneously (for action 3 and action 1, to be specific) before the first one could be fully processed by the database.

Other ways to replicate the problem:
- Shuffle the order of the first few lines of any Subject REALLY REALLY FAST.

### Status

Major problem (crashes application and leaves state of Subject transcriptions in a potential limbo) but possibly low probability of happening? I mean, what maniac would perform so many changes in one go?

...but if Tove ever takes longer than it currently does to confirm a PATCH request (e.g. user has a slow network, or the payload is megahuge), or if users act faster than the PATCH request can resolve, then we've got a problem.

Note that one sensible solution is to make the the "save changes to database" system action to trigger only once every X seconds (and only if there's no active "save changes to database" action currently happening) but that would require a major rethink of the ALICE design.

**Comment by wgranger** [comment]
Great catch! 

> Major problem (crashes application and leaves state of Subject transcriptions in a potential limbo) but possibly low probability of happening? I mean, what maniac would perform so many changes in one go?

"what maniac" - this will for sure happen. I'll plan accordingly in the frontend. Maybe when patches occur in a quick succession, only the final one should hit the backend? The state should be the same as MobX is maintaining it.
