### ISSUE TITLE
Reordering Bug

### ISSUE THREAD

**Issue by wgranger** [zooniverse/text-editor#189]
There's a pretty bad bug in the row reorganizer that occurs when reordering two rows of different heights.

<img width="500" alt="Screen Shot 2020-07-24 at 10 45 16 AM" src="https://user-images.githubusercontent.com/14099077/88409770-02dec400-cd9b-11ea-926d-db51c87bcbc7.png">

Consider the image above. Let's say I do the following:

- Grab the second line "of this can..." and drag it over the top line "Very long text that will..."
- **Immediately** when the mouse crosses onto the top row, the two rows switch places, meaning there is a moment when the mouse is dragging "of this can..." but is hovered over "Very long text..." Illustrated below:

<img width="500" alt="Screen Shot 2020-07-24 at 10 45 16 AM" src="https://user-images.githubusercontent.com/14099077/88410590-32420080-cd9c-11ea-91c1-d62fc805f3a6.png">

- When this happens, a loop occurs. The two lines attempt to switch places constantly, sometimes over 100 times, because the different row sizes give the illusion that the mouse is constantly dragging out of one line and onto another

This isn't great UX and gives the impression that something is wrong on the site. An easy fix here is to make all lines the same height by giving a type of "very long text..." ellipsis at the end of a longer text block. However, that changes the UI a bit. 

Still investigating another way to solve this issue, but I'm not positive it can be solved simply with the drag handlers I have in place.

**Comment by beckyrother** [comment]
I think that would work. Would they be able to resize the interface to be able to show the whole line of text (if it's not too too long)? It's not the best experience but I agree this is the best fix for this bug.

**Comment by wgranger** [comment]
Resizing the interface does not affect the height of each row, so each row will only show one line of text.

**Comment by beckyrother** [comment]
Right, but will it show more of the line of text? Like if the phrase "Very long text that will overflow" gets shortened to "very long text that..." would resizing eventually show more of the words that were cut off?
