### ISSUE TITLE
high severity security vulnerability: handlebars

### ISSUE THREAD

**Issue by nciemniak** [zooniverse/text-editor#202]
Relevant security alert: https://github.com/zooniverse/text-editor/network/alert/yarn.lock/handlebars/open

`handlebars` npm package needs to be bumped to 4.5.3 or later. No automatically generated dependabot PR exists. `handlebars` is an extension to the Mustache templating language, see more information about it on the npm page: https://www.npmjs.com/package/handlebars

**Comment by wgranger** [comment]
Closed with #200
