### ISSUE TITLE
high severity security vulnerability: http-proxy

### ISSUE THREAD

**Issue by nciemniak** [zooniverse/text-editor#203]
Security alert: https://github.com/zooniverse/text-editor/network/alert/yarn.lock/http-proxy/open
Dependabot PR: https://github.com/zooniverse/text-editor/pull/201

Versions prior to 1.18.1 are vunerable to Denial of Service. `http-proxy` is a proxying library that supports websockets. More info on the npm page: https://www.npmjs.com/package/http-proxy

**Comment by wgranger** [comment]
Closed with #201
