### ISSUE TITLE
Broken image cards on ALICE Projects page

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/text-editor#207]
When logged into alice.zooniverse.org/projects, image cards are broken for the majority of the projects. See screenshot via [link](https://imgur.com/a/m2k3J4y).

Looks like something weird is happening with the img URLs:

`Request URL: https://https//panoptes-uploads.zooniverse.org/project_avatar/00a63566-fef0-49ad-9602-77f634406652.jpeg`

**Comment by camallen** [comment]
This is linked to an API change and similar to a PFE changes outlined in https://github.com/zooniverse/Panoptes-Front-End/pull/5865 and https://github.com/zooniverse/Panoptes-Front-End/pull/5866
