### ISSUE TITLE
Aggregation Settings Window in Different Layouts

### ISSUE THREAD

**Issue by wgranger** [zooniverse/text-editor#38]
Currently, the Aggregation Settings window is bound to the Transcribed Text table (see the current layout below), but what happens when the two windows are resized, using the ellipsis tool, and the Transcribed Text table is more narrow? 

![Screen Shot 2019-10-17 at 3 07 49 PM](https://user-images.githubusercontent.com/14099077/67048064-23396e00-f0f9-11e9-8bba-adda7433c887.png)

We will also have an issue when the Editor changes layout modes from columns to rows. Naturally, the Transcribed Text box will be smaller underneath  the Subject viewer, leaving less space for the Aggregation Settings window to render it's natural height and width.

![Screen Shot 2019-10-17 at 4 14 18 PM](https://user-images.githubusercontent.com/14099077/67048100-32b8b700-f0f9-11e9-9e85-8a143bfd911f.png)

Tagging @beckyrother

**Comment by beckyrother** [comment]
The box should be a consistent size and appear in the same place and hopefully should be draggable: https://projects.invisionapp.com/d/main#/console/17925240/389410040/preview

Also:
- All buttons external to the modal are disabled and greyed out 50%
- Added a drag indicator at the top of the modal
- Can the view (image vs transcribed text) be resized while this window is open? Probably not?

**Comment by wgranger** [comment]
How would the view (image/transcribed text) be resized when the window is open? Would it go back to sharing the screen 50/50? That can happen.

**Comment by beckyrother** [comment]
I would expect it to keep the same view settings; otherwise we should tell the user that the view will be reset

**Comment by wgranger** [comment]
Oh I misunderstood. You were asking if the view should be able to resize with the settings window open.

It seems more natural that the window would disable any actions beneath it. However, if we find a good use case for resizing the window when the aggregation settings window is open, that can certainly happen.
