### ISSUE TITLE
How to Wrap Index Breadcrumbs?

### ISSUE THREAD

**Issue by wgranger** [zooniverse/text-editor#64]
A narrow window width can easily lead to some wonky breadcrumb wrapping. What's the best way to handle this? tagging @beckyrother

<img width="946" alt="Screen Shot 2019-12-05 at 1 25 21 PM" src="https://user-images.githubusercontent.com/14099077/70266879-f1d93800-1762-11ea-86c9-1f4e6a2f1cf4.png">

**Comment by beckyrother** [comment]
Move the breadcrumbs to above the title of the page so there's more space (everywhere, including in the editor):
![image](https://user-images.githubusercontent.com/1392130/70276739-8d27d880-1776-11ea-8495-8bad14c46cde.png)

Hopefully that fixes it! But if not [this truncation](https://codepen.io/allicarn/pen/jPowab) is what I was talking about. Nielsen Norman Group does not recommend this though so it should be a last resort.

[additional notes for future me] NNGroup breadcrumbs guidelines: https://www.nngroup.com/articles/breadcrumbs/
Nielsen Norman suggests never to wrap to multiple lines and always having a link back to the home page.

**Comment by wgranger** [comment]
Will each breadcrumb stack on top of each other vertically? So on the subjects page I would have the following breadcrumbs:

Select Project
Project Name
Workflow Name
Active Group Name (not breadcrumb)

**Comment by beckyrother** [comment]
Nope:
![image](https://user-images.githubusercontent.com/1392130/70277229-9bc2bf80-1777-11ea-8a26-4aeab3afde0a.png)

(InVision is updated with all of this also)
