### ISSUE TITLE
HTML Drag and Drop API

### ISSUE THREAD

**Issue by srallen** [zooniverse/text-editor#7]
I'd recommend investigating the HTML Drag and Drop API for the various reordering functionality the app is going to have: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API

**Comment by eatyourgreens** [comment]
Here's a good article (plus demo) about drag-and-drop with keyboard support and live region announcements.
https://www.smashingmagazine.com/2018/01/dragon-drop-accessible-list-reordering/

**Comment by wgranger** [comment]
Closed in #39
